### ISSUE TITLE
More than 1 top 1 move [1] 5r2/5p1Q/4pkp1/p7/1pb2q1P/5P2/P4RP1/3R2K1 w - -

### ISSUE THREAD

**Issue by fsmosca** [fsmosca/STS-Rating#2]
src: `STS1-STS15_LAN_v5.epd`

![image](https://user-images.githubusercontent.com/22366935/197684983-62f4c045-6f5c-45ea-876b-aba1a7708ba9.png)

```
5r2/5p1Q/4pkp1/p7/1pb2q1P/5P2/P4RP1/3R2K1 w - - bm Rb1; id "STS(v1.0) Undermine.064"; c0 "Rb1=100, Rdd2=100, Rd7=100, Re1=100, Rb2=100, Rfd2=100, Kh1=100, g4=100, h5=100, Ra1=1"; c7 "Rb1 Rdd2 Rd7 Re1 Rb2 Rfd2 Kh1 g4 h5 Ra1"; c8 "100 100 100 100 100 100 100 100 100 1"; c9 "d1b1 d1d2 d1d7 d1e1 f2b2 f2d2 g1h1 g2g4 h4h5 d1a1"; Ae "Stockish 15";
```

**Comment by tissatussa** [comment]
interesting position! indeed many moves are equal 0.00 according to my SF 15 NNUE and ShashChess 25 MCTS .. but then : what is the purpose of such position when doing a STS 'bm' test? Will other engines find Rb1 Best Move?

**Comment by fsmosca** [comment]
I am investigating these type of test position. My hardware is not that fast and my analysis is only done at 60s with multipv 10. I would like to verify this at longer movetime. Maybe you can help. If there are really more than 1 top 1 move, perhaps this test position can be replaced. Or just modify the epd, to show more than 1 bm.

**Comment by tissatussa** [comment]
i tested the position with the two engines i mentioned .. ShashChess also is SF based .. i let them reach about depth 40 and many moves are 0.00 .. i think a position is only suitable for STS when a clear bm exists .. ok, i can imagine 2 or 3 bm exist, but then all other moves must clearly be worse .. to find out if a position has a clear bm and thus will be suitable for STS, you can (must) run your engine for a very long time.

**Comment by fsmosca** [comment]
I also run it with more time with sf15.

Two or more top 1 moves are fine with me as long the theme is present. If the theme is about `Open Files and Diagonals` and the the top 1 moves are all about that theme, then we add those moves in the `bm` field. It could be, `bm Rf1 Rb1 Rad1;` for example.

I also like positions where the top moves have different evaluations. For example, top1=50cp, top2=30cp, top3=-10, top4=-25 and so on. The idea is to differentiate the strength of the engines to be tested. I can solve this by taking the standard deviation of the evaluation list. If stdev is low, the test position is not good. We still follow the theming.

There are a lot of human or engine positions that we can use to replace other positions. It just takes time, but we are not time-pressured here. The theme of this test is `Undermine`.

### Undermine
* [Undermining/Removal of Guards/Pawn Weakening problems](https://sites.google.com/site/strategictestsuite/1-undermining)
* [Wiki Undermining (chess)](https://en.wikipedia.org/wiki/Undermining_(chess))
* [Lichess Undermining](https://lichess.org/practice/intermediate-tactics/undermining/udx042D6/00n75ddn)

### Related references
* [Chess Tempo Positional Motiffs](https://chesstempo.com/positional-motifs)

**Comment by fsmosca** [comment]
Candidate positions as a replacement.

[1]

![image](https://user-images.githubusercontent.com/22366935/197679104-2cb251d9-be7c-44bc-bc0a-e7397ea4a1af.png)
r3r3/2pq2pk/2b1p1np/pp3p2/n2PP3/R1P1BPP1/Q2N2BP/R5K1 w - - bm c4;

[2]

![image](https://user-images.githubusercontent.com/22366935/197679957-088aef6d-f126-4bc8-aec2-86f65ac80c6e.png)
7r/2b1kpp1/p2p1q2/1p1RpPp1/nP2P1B1/R7/2P1Q1KP/8 w - - bm c4;

[3]

![image](https://user-images.githubusercontent.com/22366935/197681682-71fc4027-f6ce-4c2c-bed1-71d8c326575e.png)

3qr1k1/p4p1p/3p1npb/1p1Pp3/n3P3/R7/1BPN1PPP/1R1Q2K1 w - -
Two moves are close c4 and Bc1, both undermines the Knight in a4 by attacking the b5 pawn.
![image](https://user-images.githubusercontent.com/22366935/197682202-60205a5d-ade3-4d32-a301-48d10fb0d7a6.png)

[4]

![image](https://user-images.githubusercontent.com/22366935/197687975-c030b2f3-0bca-455a-a1cb-4bf2e3ff79fc.png)
1k1r4/1p2r3/p2q4/2p1p1b1/4Qn1p/1BPP1R2/PP3PPB/1K1R4 w - - bm d4
d4 can be found with a long search but challenging in 100ms

**Comment by fsmosca** [comment]
> I also run it with more time with sf15.
> 

This is what I got with mpv 10.

![image](https://user-images.githubusercontent.com/22366935/197684285-91b40aa0-4c32-430c-b095-5038082047f1.png)

I think it is safe to replace this.

**Comment by unixwizard** [comment]
I am interested in helping with this. My need is a quick way to evaluate the relative strength of engines. I care less about absolute precision than relative measure. i.e. As long as engines which score higher actually play better, I don't care if the ELO is accurate.

I have begun a depth 40 10-PV search on all 1500 positions using SF15 via Arena(which doesn't seem to be able to match up the format of the .epd best move info with the engine output, but that's a different topic). It seems that every one of them has some differences, and in some cases, the STS best move isn't even on the list of moves in the analysis.

The above questions about thematic representation are valid but not entirely helpful to my use case. I don't really care which areas have weaknesses, I just want a fast, reliable evaluation of relative ability as a total score.

Another consideration is how to assign points. If two positions are nearly equal as best move, do they both get 10's? What if there is just one move which is game winning, but the rest are positive? etc. I'll let others debate that point. :) Example: Position 2: (I apologize in advance, the analysis output is in reverse order, best move at bottom)

-     40/66	1:29:15	122,375,579k	22,852k	+6.33	Qe4-d4+  Kh8-g8  Qd4xb6  Qd7-e8  Qb6-d4  Qe8-e5  Rc1-d1  ...
-     40/49	1:29:15	122,375,579k	22,852k	+6.45	Rc1-f1  g6-g5  h3-h4  Rf5-e5  Qe4-d3  Qd7-e6  Bh6xg5  ...
-     40/65	1:29:15	122,375,579k	22,852k	+6.47	a3-a4  Kh8-g8  Bh6xf4  Nb8-c6  b4-b5  Qd7-e7  Qe4xe7  ...
-     40/65	1:29:15	122,375,579k	22,852k	+6.47	Qe4-a8  Qd7-d8  Rc1-f1  g6-g5  h3-h4  Qd8-e8  Bh6xg5  ...
-     40/85	1:29:15	122,375,579k	22,852k	+6.54	g2-g4  Rf5-e5  Qe4xf4  Qd7-e7  Rc1-f1  Re5-e1  Qf4-d4+  ...
-     40/69	1:29:15	122,375,579k	22,852k	+6.57	Kg1-h2  Kh8-g8  Bh6xf4  Nb8-c6  Rc1-d1  Qd7-e7  Qe4xc6  ...
-     40/57	1:29:15	122,375,579k	22,852k	+7.22	Rc1-d1  f4-f3  Qe4-d4+  Kh8-g8  Qd4xd6  Qd7xd6  Rd1xd6  ...
-     40/51	1:29:15	122,375,579k	22,852k	+7.60	Bh6xf4  Nb8-c6  Rc1-d1  Qd7-e7  Qe4xe7  Nc6xe7  Bf4xd6  ...
-     40/58	1:29:15	122,375,579k	22,852k	+8.37	b4-b5  Kh8-g8  Bh6xf4  Qd7-c8  Kg1-h2  Qc8-f8  Bf4-g3  ...
-     40/58	1:29:15	122,375,579k	22,852k	+48.16	c4-c5  d6xc5  b4xc5  Qd7-c6  Qe4xc6  Nb8xc6  c5xb6  Nc6-e7  ...


In any case, if you like I can post the evals here if it would be helpful. We could even split up the file among interested parties to finish the eval sooner. (I can only go as fast as my 5950x takes me) What seems to be clear is that the positional evaluations currently included are not in line with deep eval by current engines.

Thoughts?

**Comment by fsmosca** [comment]
> I am interested in helping with this. My need is a quick way to evaluate the relative strength of engines. I care less about absolute precision than relative measure. i.e. As long as engines which score higher actually play better, I don't care if the ELO is accurate.
> 
> I have begun a depth 40 10-PV search on all 1500 positions using SF15 via Arena(which doesn't seem to be able to match up the format of the .epd best move info with the engine output, but that's a different topic). It seems that every one of them has some differences, and in some cases, the STS best move isn't even on the list of moves in the analysis.
> 
I will create a tool that will save the analysis in csv format. The filename is something like:  
`pos1_d40_sf15.csv`
`pos2_d40_sf15.csv`

If somebody will try to improve the depth, they can do so increasing the existing analysis depth.

For now we will try to analyze the existing positions to a higher depths. Once we have the analysis, we can then select the good positions or whatever one wants.

I will also prepare a google sheet to monitor the progress.

See the tools folder in this repository to access the the google folder/file links.

**Comment by unixwizard** [comment]
[STSAnalysesLong40.log](https://github.com/fsmosca/STS-Rating/files/9864449/STSAnalysesLong40.log)

Here is a sample of the...ahem...verbose analysis output.

**Comment by fsmosca** [comment]
Uploaded analyze.py to analyze epd and save the analysis in csv. See the [tools](https://github.com/fsmosca/STS-Rating/tree/master/tools) folder. There is also a link to the google folder for the sts_positions sheet and csv folder to store the analysis.

**Comment by fsmosca** [comment]
> [STSAnalysesLong40.log](https://github.com/fsmosca/STS-Rating/files/9864449/STSAnalysesLong40.log)
> 
> Here is a sample of the...ahem...verbose analysis output.

I am not sure I can parse that output properly. I would like to encourage you to use in the analyze.py in the tools folder.

**Comment by fsmosca** [comment]
> Another consideration is how to assign points. If two positions are nearly equal as best move, do they both get 10's? What if there is just one move which is game winning, but the rest are positive? etc. I'll let others debate that point. :)

I am currently using an [interpolation, mapping eval to [1, 100]](https://github.com/fsmosca/STS-Rating#evaluationpoint-mapping) point system.

**Example 1, two positions are nearly equal as best.**

```
eval = [150, 145, 15, 10, 0, -2, -25, -26, -28, -50]

eval: 150, point: 100
eval: 145, point: 98
eval: 15, point: 33
eval: 10, point: 31
eval: 0, point: 26
eval: -2, point: 25
eval: -25, point: 13
eval: -26, point: 13
eval: -28, point: 12
eval: -50, point: 1
```

Example 2:  

```
eval = [700, 150, 50, 30, 25, 24, 20, 15, 8, 4]

eval: 700, point: 100
eval: 150, point: 22
eval: 50, point: 8
eval: 30, point: 5
eval: 25, point: 4
eval: 24, point: 4
eval: 20, point: 3
eval: 15, point: 3
eval: 8, point: 2
eval: 4, point: 1
```

**Comment by tissatussa** [comment]
i think this way you're heading in the wrong direction : when considering that many "bm's" the whole concept of the position having a bm is transformed .. and all those "bm's" probably will not be of the same theme .. besides that, the eval of all those moves will differ from engine (%) to engine (%), so it's not clear. Please reconsider your concept. Having a point system for (some) alternative bm's is nice though.

%) i mean a 'reference engine' like SF 15

**Comment by fsmosca** [comment]
This position `5r2/5p1Q/4pkp1/p7/1pb2q1P/5P2/P4RP1/3R2K1 w - -`  index 63 in google sts sheet will be replaced by:

```
7r/2b1kpp1/p2p1q2/1p1RpPp1/nP2P1B1/R7/2P1Q1KP/8 w - -
```
This is recorded in sts sheet as index 1498.
